name: 'Publish Debian Repository'
inputs:
  github_token:
    default: ${{ github.token }}
  source:
    default: ${{ github.repository }}
  mode:
    default: write
  directory:
    default: .
runs:
  using: composite
  steps:
    - shell: bash
      run: mkdir -p ${{ inputs.directory }}/dists/stable/main/binary-all ${{ inputs.directory }}/pool/main
    - shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
      run: |
        cd ${{ inputs.directory }}/pool/main
        cat <<< "${{ inputs.source }}" | tr ',' '\n' | tr ';' '\n' | tr ' ' '\n' | xargs -I '{}' gh api /repos/'{}'/releases --paginate | jq '.[] | .assets[] | select(.name | endswith(".deb")) | .url' -c --unbuffered | xargs wget --header "Authorization: Bearer $GH_TOKEN" --header 'Accept: application/octet-stream' --tries inf --random-wait -nc
        ls | while read -r file; do mv "$file" "$file".deb; done
    - shell: bash
      working-directory: ${{ inputs.directory }}
      run: dpkg-scanpackages --multiversion pool/main | tee $( [ ${{ inputs.mode }} = append ] && echo -a || true ) ${{ inputs.directory }}/dists/stable/main/binary-all/Packages > /dev/null
    - shell: bash
      run: gzip -9 < ${{ inputs.directory }}/dists/stable/main/binary-all/Packages > ${{ inputs.directory }}/dists/stable/main/binary-all/Packages.gz
    - shell: bash
      run: |
        cd ${{ inputs.directory }}/dists/stable
        {
          do_hash() {
              HASH_NAME=$1
              HASH_CMD=$2
              echo "${HASH_NAME}:"
              for f in $(find -type f); do
                  f=$(echo $f | cut -c3-) # remove ./ prefix
                  if [ "$f" = "Release" ]; then
                      continue
                  fi
                  echo " $(${HASH_CMD} ${f}  | cut -d" " -f1) $(wc -c $f)"
              done
          }
          cat << EOF
        Origin: GitHub ${{ github.repository_owner }}
        Label: ${{ github.repository_owner }}
        Suite: stable
        Codename: stable
        Version: 1.0
        Architectures: all
        Components: main
        Description: A software repository hosting packages from github
        Date: $(date -Ru)
        EOF
          do_hash "MD5Sum" "md5sum"
          do_hash "SHA1" "sha1sum"
          do_hash "SHA256" "sha256sum"
        } > Release
